// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicioVentas.Infrastructure.Persistence;

#nullable disable

namespace ServicioVentas.Infrastructure.Migrations
{
    [DbContext(typeof(ServicioVentasDbContext))]
    partial class ServicioVentasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServicioVentas.Domain.Models.AuditoriaEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntidadId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ValoresAnterioresJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevosJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Modulo", "Accion");

                    b.ToTable("AUDITORIA_EVENTO", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abierta")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoCierre")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UsuarioAperturaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Abierta")
                        .IsUnique()
                        .HasFilter("[Abierta] = 1");

                    b.HasIndex("UsuarioAperturaId");

                    b.HasIndex("UsuarioCierreId");

                    b.ToTable("CAJA", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ImpuestoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ImpuestoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CATEGORIA_PRODUCTO", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Color = "#2563eb",
                            Icono = "bottle",
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Color = "#d97706",
                            Icono = "basket",
                            Nombre = "Almacen"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Color = "#2563eb",
                            Icono = "milk",
                            Nombre = "Lacteos"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Color = "#16a34a",
                            Icono = "cleaner",
                            Nombre = "Limpieza"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Color = "#ea580c",
                            Icono = "bread",
                            Nombre = "Panaderia"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Color = "#9333ea",
                            Icono = "candy",
                            Nombre = "Golosinas"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Color = "#64748b",
                            Icono = "more",
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Deuda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.ConfiguracionNegocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AplicarImpuestosEnVentas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ColorPrincipal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#ef0000");

                    b.Property<bool>("ConfirmarEliminarItemCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("DescuentoMaximoPermitido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(20m);

                    b.Property<string>("DiasAtencion")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("EnviarEstadisticasAnonimas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("FormatoFecha")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("dd/MM/yyyy");

                    b.Property<string>("FormatoHora")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("24");

                    b.Property<string>("HorarioApertura")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HorarioCierre")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("ImprimirResumenCerrarCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("MantenerClienteAlFinalizarVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MontoMinimoAperturaCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("MostrarMensajesAyuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("MostrarStockEnBusquedaProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("PedirCantidadAlAgregarProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PedirMotivoCerrarCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RedondeoTotal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0.05");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("CONFIGURACION_NEGOCIO", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.ConfiguracionTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnchoPapelMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(80);

                    b.Property<bool>("CorteAutomatico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("ImpresoraId")
                        .HasColumnType("int");

                    b.Property<string>("ImpresoraNombreSistema")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("ImprimirCajeroTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImprimirClienteTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImprimirCopiaTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ImprimirDatosNegocioTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImprimirDescuentoRecargoTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImprimirDesgloseImpuestosTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImprimirFechaHoraTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImprimirMedioPagoTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImprimirMensajeCierreTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImprimirNumeroTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImprimirSubtotalTotalTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("LetraGrandePantallaTactil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MensajeTicket")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("UsaAnchoPersonalizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("UsaTicketTermico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("VistaPreviaAntesImprimir")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("ImpresoraId");

                    b.ToTable("CONFIGURACION_TICKET", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Impresora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AnchoPapelMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(80);

                    b.Property<string>("Conexion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("CorteAutomatico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("DensidadImpresion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Media");

                    b.Property<bool>("EsPredeterminada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Modelo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NombreSistema")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Puerto")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Ticket");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("NombreSistema");

                    b.ToTable("IMPRESORA", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Impuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EsPredeterminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EsPredeterminado")
                        .IsUnique()
                        .HasFilter("[EsPredeterminado] = 1");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("IMPUESTO", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            EsPredeterminado = true,
                            FechaCreacion = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "IVA General",
                            Porcentaje = 21m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            EsPredeterminado = false,
                            FechaCreacion = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "IVA Reducido",
                            Porcentaje = 10.5m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            EsPredeterminado = false,
                            FechaCreacion = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Exento",
                            Porcentaje = 0m
                        });
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.MarcaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MARCA_PRODUCTO", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MEDIO_PAGO", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MOVIMIENTO_CAJA", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("StockAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockNuevo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProductoId", "Fecha");

                    b.ToTable("MOVIMIENTO_STOCK", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarra")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImpuestoId")
                        .HasColumnType("int");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoBarra")
                        .IsUnique()
                        .HasFilter("[CodigoBarra] IS NOT NULL");

                    b.HasIndex("CodigoInterno")
                        .IsUnique()
                        .HasFilter("[CodigoInterno] IS NOT NULL");

                    b.HasIndex("ImpuestoId");

                    b.HasIndex("MarcaId");

                    b.ToTable("PRODUCTO", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("VENTA", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImporteImpuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImporteNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ImpuestoId")
                        .HasColumnType("int");

                    b.Property<string>("ImpuestoNombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("ImpuestoPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImpuestoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("VENTA_DETALLE", (string)null);
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.AuditoriaEvento", b =>
                {
                    b.HasOne("ServicioVentas.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Caja", b =>
                {
                    b.HasOne("ServicioVentas.Domain.Models.Usuario", "UsuarioApertura")
                        .WithMany("CajasAbiertas")
                        .HasForeignKey("UsuarioAperturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioVentas.Domain.Models.Usuario", "UsuarioCierre")
                        .WithMany("CajasCerradas")
                        .HasForeignKey("UsuarioCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.CategoriaProducto", b =>
                {
                    b.HasOne("ServicioVentas.Domain.Models.Impuesto", "Impuesto")
                        .WithMany("Categorias")
                        .HasForeignKey("ImpuestoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Impuesto");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.ConfiguracionTicket", b =>
                {
                    b.HasOne("ServicioVentas.Domain.Models.Impresora", "Impresora")
                        .WithMany()
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Impresora");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.MovimientoCaja", b =>
                {
                    b.HasOne("ServicioVentas.Domain.Models.Caja", "Caja")
                        .WithMany("Movimientos")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioVentas.Domain.Models.Usuario", "Usuario")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.MovimientoStock", b =>
                {
                    b.HasOne("ServicioVentas.Domain.Models.Producto", "Producto")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioVentas.Domain.Models.Usuario", "Usuario")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Producto", b =>
                {
                    b.HasOne("ServicioVentas.Domain.Models.CategoriaProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ServicioVentas.Domain.Models.Impuesto", "Impuesto")
                        .WithMany("Productos")
                        .HasForeignKey("ImpuestoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ServicioVentas.Domain.Models.MarcaProducto", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Impuesto");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Venta", b =>
                {
                    b.HasOne("ServicioVentas.Domain.Models.Caja", "Caja")
                        .WithMany("Ventas")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioVentas.Domain.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServicioVentas.Domain.Models.MedioPago", "MedioPago")
                        .WithMany("Ventas")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioVentas.Domain.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Cliente");

                    b.Navigation("MedioPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.VentaDetalle", b =>
                {
                    b.HasOne("ServicioVentas.Domain.Models.Impuesto", "Impuesto")
                        .WithMany()
                        .HasForeignKey("ImpuestoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ServicioVentas.Domain.Models.Producto", "Producto")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServicioVentas.Domain.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impuesto");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Caja", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Impuesto", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.MarcaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.MedioPago", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Producto", b =>
                {
                    b.Navigation("MovimientosStock");

                    b.Navigation("VentaDetalles");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Usuario", b =>
                {
                    b.Navigation("CajasAbiertas");

                    b.Navigation("CajasCerradas");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("MovimientosStock");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("ServicioVentas.Domain.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
